version: "3"
services:
  nginx:
    image: frederickwong/learning:latest
    restart: unless-stopped
    environment:
      - NGINX_RELOAD_DELAY=15s
      - NGINX_PATH_TO_MONITOR=/etc/nginx/conf.d /etc/letsencrypt/archive
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/conf:/etc/nginx/conf.d
      - ./data/certs:/etc/letsencrypt/archive
    ports:
      - 80:80
      - 433:433