name: Learning
on: push
# filters:
#   branches:
#     ignore: /.*/
#   tags:
#     only: /^v\d+\.\d+\.\d+$/
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            NGINX_TAG:1.23.4-alpine
          platforms: linux/arm64,linux/amd64,linux/arm/v7
          tags: frederickwong/learning:latest,frederickwong/learning:0.1.1
