name: Learning
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platform:
            - linux/arm64
            - linux/amd64
            - linux/arm/v7
          tags:
            - frederickwong/learning:latest
            - frederickwong/learning:0.1.1
